/*
 Generated by typeshare 1.13.4
*/

export interface AdaptiveShedPayload {
	level: number;
	kspFps: number;
	reason: string;
}

/**
 * Layer mask. Mirrors `Kerbcam.CameraLayers` on the plugin side.
 * Receiving clients use this for both the rendered-layer status reports
 * and per-camera layer requests.
 */
export enum Layer {
	Near = "NEAR",
	Scaled = "SCALED",
	Galaxy = "GALAXY",
}

/**
 * Per-camera snapshot pushed by the sidecar on every state change
 * (operator API call, adaptive shed, vessel change). Same shape served
 * by `GET /cameras` so client UIs can treat the two interchangeably.
 */
export interface CameraState {
	flightId: number;
	partName: string;
	partTitle: string;
	cameraName: string;
	vesselName: string;
	/** Currently-rendered layers (effective after adaptive shedding). */
	layers: Layer[];
	/**
	 * Operator-requested layer mask — the ceiling adaptive shedding
	 * can reduce below. UIs use this to show "scaled is *requested* but
	 * not *active* right now due to fps".
	 */
	operatorLayers: Layer[];
	/**
	 * Currently-rendered dimensions (effective after adaptive
	 * resolution downscale). Equal to `operatorWidth` × `operatorHeight`
	 * when no auto-shed is in effect.
	 */
	renderWidth: number;
	renderHeight: number;
	/**
	 * Operator-requested render size — ceiling adaptive downscale can
	 * reduce below.
	 */
	operatorWidth: number;
	operatorHeight: number;
}

export interface CameraSnapshotPayload {
	cameras: CameraState[];
}

export interface CameraStateChangedPayload {
	state: CameraState;
}

export interface ErrorPayload {
	message: string;
}

export interface FlightIdPayload {
	flightId: number;
}

export interface HelloPayload {
	sidecarVersion: string;
	encoderBackend: string;
}

export interface SetLayersPayload {
	flightId: number;
	layers: Layer[];
}

export interface SetRenderSizePayload {
	flightId: number;
	width: number;
	height: number;
}

/** Messages sent FROM the client TO the sidecar. */
export type ClientMessage = 
	/**
	 * First message on a new data channel. Sidecar replies with `Hello`
	 * + a `CameraSnapshot` so the client gets server version + every
	 * camera's full state on one round-trip.
	 */
	| { type: "hello", content?: undefined }
	/**
	 * Override the operator layer mask for one camera. Server-wide
	 * state — all consumers see the change.
	 */
	| { type: "set-layers", content: SetLayersPayload }
	/**
	 * Override the operator render size for one camera. Even pixels
	 * only (H.264 chroma); server caps at the ring's allocated max.
	 */
	| { type: "set-render-size", content: SetRenderSizePayload }
	/**
	 * Request an IDR (keyframe) on the next encode tick. Browsers send
	 * this when they've dropped enough frames to be unable to decode
	 * the current P-frame chain. Sidecar forwards to the camera's
	 * encoder.
	 */
	| { type: "request-keyframe", content: FlightIdPayload };

/** Messages sent FROM the sidecar TO the client. */
export type ServerMessage = 
	/**
	 * Reply to `Hello`. Carries server version + the active encoder
	 * backend's name.
	 */
	| { type: "hello", content: HelloPayload }
	/**
	 * Full snapshot of every currently-attached camera. Sent in reply
	 * to `Hello` and on any structural change (vessel switch, ring
	 * added/removed).
	 */
	| { type: "camera-snapshot", content: CameraSnapshotPayload }
	/**
	 * Single-camera state change. Sent when an operator request applies
	 * or adaptive shedding kicks in. Lets clients update their UI
	 * without re-fetching the whole snapshot.
	 */
	| { type: "camera-state-changed", content: CameraStateChangedPayload }
	/**
	 * Adaptive shedding level changed. Reason is human-readable
	 * ("ksp-fps-low", "ksp-fps-recovered") so client UIs can show
	 * *why* quality changed rather than just *that* it did.
	 */
	| { type: "adaptive-shed", content: AdaptiveShedPayload }
	/**
	 * Malformed / unknown client message. Includes the offending
	 * payload so the client can log it.
	 */
	| { type: "error", content: ErrorPayload };

