/*
 Generated by typeshare 1.13.4
*/

export interface AdaptiveShedPayload {
	level: number;
	kspFps: number;
	reason: string;
}

/**
 * Layer mask. Mirrors `Kerbcam.CameraLayers` on the plugin side.
 * Receiving clients use this for both the rendered-layer status reports
 * and per-camera layer requests.
 */
export enum Layer {
	Near = "NEAR",
	Scaled = "SCALED",
	Galaxy = "GALAXY",
}

/**
 * Per-camera snapshot pushed by the sidecar on every state change
 * (operator API call, adaptive shed, vessel change). Same shape served
 * by `GET /cameras` so client UIs can treat the two interchangeably.
 * 
 * Capability fields (`supports_zoom`, `supports_pan`) let clients
 * render controls only for features each part actually offers — a
 * fixed-FoV camera shouldn't get a zoom slider, a non-steerable one
 * shouldn't get a pan stick.
 */
export interface CameraState {
	flightId: number;
	partName: string;
	partTitle: string;
	cameraName: string;
	vesselName: string;
	/** Currently-rendered layers (effective after adaptive shedding). */
	layers: Layer[];
	/**
	 * Operator-requested layer mask — the ceiling adaptive shedding
	 * can reduce below. UIs use this to show "scaled is *requested* but
	 * not *active* right now due to fps".
	 */
	operatorLayers: Layer[];
	/**
	 * Currently-rendered dimensions (effective after adaptive
	 * resolution downscale). Equal to `operatorWidth` × `operatorHeight`
	 * when no auto-shed is in effect.
	 */
	renderWidth: number;
	renderHeight: number;
	/**
	 * Operator-requested render size — ceiling adaptive downscale can
	 * reduce below.
	 */
	operatorWidth: number;
	operatorHeight: number;
	/**
	 * Whether the part's Hullcam module supports runtime FoV changes
	 * (i.e. it's a `MuMechModuleHullCameraZoom`, not the fixed base
	 * `MuMechModuleHullCamera`). 19 of 21 stock parts do.
	 */
	supportsZoom: boolean;
	/** Current effective FoV in degrees. */
	fov: number;
	/**
	 * FoV bounds the operator can choose between. Wider than the
	 * camera's "default" — these come from the Hullcam part config.
	 * Equal to `fov` when `supports_zoom == false`.
	 */
	fovMin: number;
	fovMax: number;
	/**
	 * Whether the part supports pan/tilt (kerbcam-side mod extension —
	 * no stock Hullcam parts are steerable, but the extended mod adds
	 * pan to specific parts). False on every shipping part today;
	 * clients should hide pan controls until this flips true.
	 */
	supportsPan: boolean;
	panYaw: number;
	panPitch: number;
	panYawMin: number;
	panYawMax: number;
	panPitchMin: number;
	panPitchMax: number;
	/**
	 * Current encoder bitrate target in bits per second. Equals
	 * `target_bitrate_bps` after the consume loop applies receiver
	 * feedback; the two diverge briefly between a REMB arriving and
	 * the consume loop's next tick. Zero when no encoder is running
	 * yet (no subscribers).
	 */
	encoderBitrateBps: number;
	/**
	 * Bandwidth target derived from receivers' REMB feedback (min
	 * across active subscribers). Drives the encoder when
	 * significantly diverged. Zero until the first REMB packet
	 * arrives — encoder falls back to the sidecar's CLI default.
	 */
	targetBitrateBps: number;
	/**
	 * Effective degrade level (max across subscribers' SetDegrade
	 * requests). 0.0 = perfect, 1.0 = max degradation. Applied
	 * alongside operator render-size + adaptive shed; the encoder
	 * multiplies its effective bitrate by `(1 - 0.7 * level)` and
	 * skips fan-out for a fraction of frames at high levels.
	 */
	degradeLevel: number;
}

export interface CameraSnapshotPayload {
	cameras: CameraState[];
}

export interface CameraStateChangedPayload {
	state: CameraState;
}

export interface ErrorPayload {
	message: string;
}

export interface FlightIdPayload {
	flightId: number;
}

export interface HelloPayload {
	sidecarVersion: string;
	encoderBackend: string;
}

export interface SetDegradePayload {
	flightId: number;
	/**
	 * 0.0 = perfect quality, 1.0 = maximum degradation. Caps and
	 * is per-subscriber: the sidecar applies max across active
	 * subscribers so the noisiest consumer's request wins (same
	 * pattern as REMB picking the min bandwidth).
	 */
	level: number;
}

export interface SetFovPayload {
	flightId: number;
	fov: number;
}

export interface SetLayersPayload {
	flightId: number;
	layers: Layer[];
}

export interface SetPanPayload {
	flightId: number;
	yaw: number;
	pitch: number;
}

export interface SetRenderSizePayload {
	flightId: number;
	width: number;
	height: number;
}

/** Messages sent FROM the client TO the sidecar. */
export type ClientMessage = 
	/**
	 * First message on a new data channel. Sidecar replies with `Hello`
	 * + a `CameraSnapshot` so the client gets server version + every
	 * camera's full state on one round-trip.
	 */
	| { type: "hello", content?: undefined }
	/**
	 * Override the operator layer mask for one camera. Server-wide
	 * state — all consumers see the change.
	 */
	| { type: "set-layers", content: SetLayersPayload }
	/**
	 * Override the operator render size for one camera. Even pixels
	 * only (H.264 chroma); server caps at the ring's allocated max.
	 */
	| { type: "set-render-size", content: SetRenderSizePayload }
	/**
	 * Set the camera's field-of-view (degrees). Silently ignored for
	 * parts whose Hullcam module is the fixed base (`supportsZoom ==
	 * false`); clients are expected to clamp to `fovMin / fovMax`
	 * from the camera's `CameraState` before sending.
	 */
	| { type: "set-fov", content: SetFovPayload }
	/**
	 * Pan/tilt the camera (yaw and pitch, both degrees from the
	 * part's resting forward). No stock Hullcam parts support this
	 * yet — the message is ignored until the planned mod extension
	 * adds steerable mounts to specific parts. Clients should hide
	 * pan controls until `supportsPan == true` for the camera.
	 */
	| { type: "set-pan", content: SetPanPayload }
	/**
	 * Request artificial signal degradation. 0.0 = perfect quality,
	 * 1.0 = maximum degradation. Per-subscriber: the sidecar
	 * applies max across active subscribers (slowest consumer
	 * wins, same pattern as REMB bandwidth). Lets consumers signal
	 * to the sidecar "I want to look like the in-game CommNet
	 * antenna is struggling"; sidecar takes the opportunity to
	 * reduce bitrate + skip frames, which both creates the
	 * signal-loss aesthetic AND saves encoder CPU.
	 */
	| { type: "set-degrade", content: SetDegradePayload }
	/**
	 * Request an IDR (keyframe) on the next encode tick. Browsers send
	 * this when they've dropped enough frames to be unable to decode
	 * the current P-frame chain. Sidecar forwards to the camera's
	 * encoder.
	 */
	| { type: "request-keyframe", content: FlightIdPayload };

/** Messages sent FROM the sidecar TO the client. */
export type ServerMessage = 
	/**
	 * Reply to `Hello`. Carries server version + the active encoder
	 * backend's name.
	 */
	| { type: "hello", content: HelloPayload }
	/**
	 * Full snapshot of every currently-attached camera. Sent in reply
	 * to `Hello` and on any structural change (vessel switch, ring
	 * added/removed).
	 */
	| { type: "camera-snapshot", content: CameraSnapshotPayload }
	/**
	 * Single-camera state change. Sent when an operator request applies
	 * or adaptive shedding kicks in. Lets clients update their UI
	 * without re-fetching the whole snapshot.
	 */
	| { type: "camera-state-changed", content: CameraStateChangedPayload }
	/**
	 * Adaptive shedding level changed. Reason is human-readable
	 * ("ksp-fps-low", "ksp-fps-recovered") so client UIs can show
	 * *why* quality changed rather than just *that* it did.
	 */
	| { type: "adaptive-shed", content: AdaptiveShedPayload }
	/**
	 * Malformed / unknown client message. Includes the offending
	 * payload so the client can log it.
	 */
	| { type: "error", content: ErrorPayload };

